
# See http://about.travis-ci.org/docs/user/build-configuration/
dist: bionic

language: scala

scala:
  - 3.0.0-M3
  - 2.13.4

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - tom@sfxcode.com
jdk:
  - openjdk11
  - openjdk8



